services:
  - type: web
    name: chatbot-back
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: dpg-csmvsb8gph6c73fqn11g-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: serverone
      - key: DB_USER
        value: serverone_user
      - key: DB_PASSWORD
        value: VWnEZLO3KB1WSdUG81UgGK2M4WxAlV23
      - key: GEMINI_API_KEY
        value: AIzaSyBTKjh1PGtHoMjKP1pOnGBaQoPmsnQD4oY
